# Generated by Django 3.2 on 2022-01-09 09:09

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(editable=False, max_length=32)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=20)),
                ('address_street_1', models.CharField(max_length=80)),
                ('address_street_2', models.CharField(blank=True, max_length=80, null=True)),
                ('address_town_city', models.CharField(max_length=40)),
                ('address_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('address_country', django_countries.fields.CountryField(max_length=2)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_weight_g', models.IntegerField(default=0)),
                ('order_items_ship_in_packet', models.BooleanField(default=False)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_zone_no', models.IntegerField(default=0)),
                ('shipping_zone_name', models.IntegerField(default=0)),
                ('country_list', models.CharField(max_length=80)),
                ('packet_limit_g', models.IntegerField(default=0)),
                ('parcel_limit_g', models.IntegerField(default=0)),
                ('parcel_excess_limit_g', models.IntegerField(default=0)),
                ('parcel_excess_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('parcel_excess_basecost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('packet_cost_00100g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('packet_cost_00250g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('packet_cost_00500g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('packet_cost_01000g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('packet_cost_01500g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('packet_cost_02000g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('parcel_cost_00100g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('parcel_cost_00250g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('parcel_cost_00500g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('parcel_cost_01000g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('parcel_cost_01500g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('parcel_cost_02000g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('parcel_cost_02500g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('parcel_cost_03000g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('parcel_cost_03500g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('parcel_cost_04000g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('parcel_cost_04500g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('parcel_cost_05000g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('parcel_cost_15000g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('parcel_cost_20000g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('lineitem_weight_g', models.IntegerField()),
                ('lineitem_ship_in_packet', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
