from django import forms
from .models import UserProfile


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('user',)

def __init__(self, *args, **kwargs):
    """
    Add placeholders and classses, remove autogenerated labels
    and set auto focus on first field.
    """
    super().__init__(*args, **kwargs)
    placeholders = {
        'default_email': 'Email Address',
        'default_phone_no': 'Telephone Number',
        'default_address_street_1': 'Street Address 1',
        'default_address_street_2': 'Street Address 2',
        'default_address_town_city': 'Town or City Name',
        'default_address_postcode': 'Post or Zip Code',
        'default_address_country': 'Country',
    }

    self.fields['default_phone_no'].widget.attrs['autofocus'] = True
    for field in self.fields:
        if self.fields[field].required:
            placeholder = f'{placeholders[field]} *'
        else:
            placeholder = placeholders[field]
        self.fields[field].widget.attrs['placeholder'] = placeholder
        self.fields[field].widget.attrs['class'] = 'profile-form-input'
        self.fields[field].label = False
