from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('full_name', 'email', 'phone_no',
                  'address_street_1', 'address_street_2',
                  'address_town_city', 'address_postcode',
                  'address_country',)

def __init__(self, *args, **kwargs):
    """
    Add placeholders and classses, remove autogenerated labels
    and set auto focus on first field.
    """
    super().__init__(*args, **kwargs)
    placeholders = {
        'full_name': 'Full Name',
        'email': 'Email Address',
        'phone_no': 'Telephone Number',
        'address_street_1': 'Street Address 1',
        'address_street_2': 'Street Address 2',
        'address_town_city': 'Town or City Name',
        'address_postcode': 'Post or Zip Code',
        'address_country': 'Country',
    }

    self.fields['full_name'].widget.attrs['autofocus'] = True
    for field in self.fields:
        if self.fields[field].required:
            placeholder = f'{placeholders[field]} *'
        else:
            placeholder = placeholders[field]
        self.fields[field].widget.attrs['placeholder'] = placeholder
        self.fields[field].widget.attrs['class'] = 'stripe-style-input'
        self.fields[field].label = False