# Generated by Django 3.2 on 2022-01-23 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_tag', models.CharField(max_length=254)),
                ('category_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('bio', models.TextField(max_length=10000)),
                ('img_url', models.URLField(blank=True, max_length=1024)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField(max_length=10000)),
                ('unitcost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight_g', models.DecimalField(decimal_places=0, max_digits=6)),
                ('ship_in_packet', models.BooleanField(default=False)),
                ('img_url', models.URLField(blank=True, max_length=1024)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('creator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.creator')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254)),
                ('salesmargin', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('stockcount', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('item_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.item')),
            ],
        ),
    ]
